### ISSUE TITLE
[Webhook] Get method

### ISSUE THREAD

**Issue by florentgarin** [docdoku/docdoku-web-front#18]
GET method is not sent (onchange event syndrome?) when creating a simple webhook.

**Comment by mguimard** [comment]
Actually its not yet implemented yet on server side. I was wondering wether removing it or not from the front app.. Does it make sense to have the simple HTTP webhook sending some notification payloads with a GET method?

**Comment by florentgarin** [comment]
Well, most of the time webhooks are implemented using POST. But adding the GET feature is almost free so why not add it just in case of it is needed?

**Comment by mguimard** [comment]
Yeah sure, this can be achieved with GET. I will pass the notification parameters as uri params.

**Comment by mguimard** [comment]
Done in https://github.com/docdoku/docdoku-plm/commit/fdd113beded895b3e6f3607d827b4a6f2a922cd1
