### ISSUE TITLE
NotFoundException error 500 while trying to search by template

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#21]
When doing a search setting the template, there is an error 500 (Unhandled system error : org.glassfish.jersey.server.ServerRuntime$2.run threw javax.ws.rs.NotFoundException: HTTP 404 Not Found in ServerRuntime.java at line 323) on the web service http://server/eplmp-server-rest/api/workspaces/workspacename/parts/search/&from=0&size=10000; the exception is displayed to the user in a red block and the page is empty.

**Comment by mguimard** [comment]
It seems that the generated URL is not correct it should be

?from=0&size=10000; instead of &from=0&size=10000;

That clearly explains the 404 error.

**Comment by mguimard** [comment]
fixed by a594f43d0a5e9084e3214ac721fce31148339cc1
