### ISSUE TITLE
User defined function crash on a run for latest released of a product

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#22]
User defined function crash on a run for latest released of a product, the web service called
https://server/eplmp-server-rest/api/workspaces/workspacename/products/productname/filter?configSpec=latest-released&depth=10&path=-1 return a 204 no content and an error in the console TypeError: a.first(...) is undefined 
This error doesn't happen on every product, only for product of parts linked to parts not released.

**Comment by mguimard** [comment]
The server doesn't send the product structure if some part in the tree has not been released. The UI should handle that case and tell the user that we cannot run his aggregations.
