### ISSUE TITLE
Errors on query building for parts

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#23]
Errors on query building for parts : 
- The export list of article does not take into account the "group by" and "order by", the displayed data is different in the list and in the exported file
- All the attribute added in the query are not placed in the column they are meant to be in the exported file (in the list it works fine); Found problem : the column Standard (true/false) is empty and all the columns to the right are moved by one case to the left, which is making the data false
- The column lifecycle return an url in localhost http://localhost:8080/eplmp-server-rest/documents/workspace/1/A
- Adding deliverable element in the context input block the search : JS error : Error: Missing filters list
- When hiding the query builder, the page return to the classic list and not the filtered list; and when you show the query builder again, the filtered list is shown again but the filter of the query are empty

**Comment by mguimard** [comment]
>The export list of article does not take into account the "group by" and "order by", the displayed data is different in the list and in the exported file

This is expected. The group by and order by clauses does are not applied to the xls export file. Maybe this should be displayed to inform the user.

> All the attribute added in the query are not placed in the column they are meant to be in the exported file (in the list it works fine); Found problem : the column Standard (true/false) is empty and all the columns to the right are moved by one case to the left, which is making the data false

This is a server issue, I'm raising an issue on the appropriate project.
https://github.com/docdoku/docdoku-plm/issues/1124

> The column lifecycle return an url in localhost http://localhost:8080/eplmp-server-rest/documents/workspace/1/A

Something must be wrong in the server configuration (see the "codebase" property in the configuration wiki page)

> Adding deliverable element in the context input block the search : JS error : Error: Missing filters list

This seems to be a bug in the UI. Did you add a context clause ? (it's mandatory to have a deliverable context, with some path attributes in the deliverable structure, if that's not the case the deliverable attributes clause  should not appear)

> When hiding the query builder, the page return to the classic list and not the filtered list; and when you show the query builder again, the filtered list is shown again but the filter of the query are empty

Hiding the query builder shows the default part list, no problem with that. After re-opening, the filtered list should be removed and query should be cleared. This is a bug.
