### ISSUE TITLE
Errors on quick search

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#24]
Errors on quick search for parts : 
- By part number does not get all the parts which contains the chosen string (example the string 'test' return the parts 'test', 'test1', 'test2' but not 'test_1', 'test_2'..)
- By author name get the same results for 2 different accounts with the same account name
- By creation date / modification date / standard part : no filter (the only displayed the parts which have been already checked in at least once)
- By template : there is an exception displayed 
Unhandled system error : org.glassfish.jersey.server.ServerRuntime$2.run threw javax.ws.rs.NotFoundException: HTTP 404 Not Found in ServerRuntime.java at line 323

**Comment by mguimard** [comment]
* By part number: I can reproduce it. it's quite frustrating. We should be more permissive
* By author name: Tried but I GET a similar 404
* By template: I can reproduce it
* By date: similar 404

**Comment by mguimard** [comment]
mostly resolved by 5f7026a9d0da35956a63ac5347e01498914f511a

Still need to be more permissive on search. Will be related to https://github.com/docdoku/docdoku-plm/issues/1137.
Closing issue
