### ISSUE TITLE
Document Collection JS Error

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#26]
After creating a document collection (with the button "Create a baseline"), even if I select latest checked in or latest released documents, I can add any type of document, i can also check in check out a document to add it multiple times.
After saving the documents selected, when i click again on the buttons to add or save the collection, i get a JS Error : TypeError: App.config.documentBaselineInProgress is undefined

**Comment by mguimard** [comment]
To be reproduced
