### ISSUE TITLE
Websocket and JWT refresh

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#28]
Errors found on chat with User 1 on firefox (v56), User 2 on chromium (v48) :
After logging in and wait at least the duration of the timeout, with 2 users, while changing page for the user 1 I am redirected to the workspace administration page (normal), I look at the coworkers online and see every one online; for the user 2, the user 1 is now offline.
After that, when I log out / log in for user 1, no coworkers are shown as online, and after changing page for the user 2, every coworkers are online. When the user 2 log out / log in, the 2 users see each other online normally.

**Comment by mguimard** [comment]
To be reproduced

**Comment by mguimard** [comment]
fixed
