### ISSUE TITLE
Error on creation and deletion of effectivity

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#35]
I can click multiple times on the create button of an effectivity on a part, the popup of creation is still open and all the effectivity are created.
I can click multiple times on the delete button of an effectivity while the popup of confirmation is open (it open multiple times the popup) and when I confirm the deletion of an effectity already deleted, there is an error shown : 
Unhandled system error : org.polarsys.eplmp.server.EffectivityManagerBean.deleteEffectivity threw java.lang.NullPointerException in EffectivityManagerBean.java at line 318

**Comment by mguimard** [comment]
Button should be disabled once clicked to avoid that problems.
