### ISSUE TITLE
Substitute number of element in assembly of part not reflected in configuration and baseline

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#40]
When choosing the elements of a configuration and baseline, the number of substitute elements in the defined assembly of a part is not reflected in the number of substitute elements of the configuration or baseline.

**Comment by mguimard** [comment]
Reproduced on my local environment. Seems that it's a server bug, the "amount" is always 1 in the xhr responses. Moving this issue to the server repo https://github.com/docdoku/docdoku-plm/issues/1125
