### ISSUE TITLE
Adding new part to an assembly is not reflected on configuration and baselines

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#41]
Adding a new part in an assembly of a part does not modify the configuration and baselines for this part, and does not take into account the new part added; it is needed to add new configuration or baseline to see it.

**Comment by mguimard** [comment]
Adding new part to an assembly is not reflected on configuration and baselines #41 ... and it should not be !  Configurations and baselines MUST NOT be affected by this changes.
