### ISSUE TITLE
Upload of a large CAD file block the conversion

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#44]
An upload of a large CAD file attached to a part goes beyong the timeout of authentication and I am sent back to the admin page, the file conversion stopped.

**Comment by mguimard** [comment]
To be reproduced

**Comment by mguimard** [comment]
The JWT lifetime doesn't affect the conversion process as it's asynchronous. However, uploading large files may results in an OutOfMemoryException. Opening an other issue in the appropriate repository
