### ISSUE TITLE
Error in visio call between 2 different users

### ISSUE THREAD

**Issue by hobywhan** [docdoku/docdoku-web-front#46]
Test with 2 computers and 2 different webcam : 
It works the first time, when the user 1 close the call window, he does not see the user connected and the user 2 see every users online; without changing the page, none of the 2 users can call the other back.
When calling, sometimes I get 'null' of 'undefined' instead of the login and/or workspace.
When trying with only one webcam, it does not work.

**Comment by mguimard** [comment]
Seems that user 2 gets disconnected from the websocket after user1 ends the conversation. Is there any logs or errors in user2 console ?

**Comment by mguimard** [comment]
Fixed in https://github.com/docdoku/docdoku-web-front/pull/63 and https://github.com/polarsys/eplmp/pull/40
