### ISSUE TITLE
[npm run dev] Cache access denied 

### ISSUE THREAD

**Issue by ludoBarel** [docdoku/docdoku-web-front#70]
When i've tried to execute `npm run dev` an error shown up ` permission denied, mkdir '~/.cache/bower/registry/registry.bower.io/lookup'`. So, i've used `sudo chmod -R 777 ~/.cache/` and the `npm run dev` ran successfully.

**Comment by mguimard** [comment]
Closing issue as it is not related to this project. This seems to be a NodeJS installation issue.
