### ISSUE TITLE
npm run dev don't work : running "watch:dev" (watch) task Waiting...

### ISSUE THREAD

**Issue by ytuquet** [docdoku/docdoku-web-front#83]
Hello,

I have a problem when i trying to install docdoku web front.

When i launch the comand npm run dev, the process are bloking on : 
running "watch:dev" (watch) task
Waiting...

See the result of command below : 

root@**********:/home/canon/workdir/docdoku-web-front# npm run dev

> docdokuplm@1.1.0 predev /home/canon/workdir/docdoku-web-front
> npm install

npm WARN lifecycle docdokuplm@1.1.0~postinstall: cannot run in wd docdokuplm@1.1.0 bower install (wd=/home/canon/workdir/docdoku-web-front)
npm WARN grunt-connect-proxy@0.2.0 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-execute@0.2.2 requires a peer of grunt@~0.4.1 but none is installed. You must install peer dependencies yourself.

audited 1183 packages in 2.871s
found 25 vulnerabilities (4 low, 20 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> docdokuplm@1.1.0 dev /home/canon/workdir/docdoku-web-front
> grunt serve

Running "serve" task

Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "less:accountManagement" (less) task
>> 1 stylesheet created.

Running "less:changeManagement" (less) task
>> 1 stylesheet created.

Running "less:documentManagement" (less) task
>> 1 stylesheet created.

Running "less:documents" (less) task
>> 1 stylesheet created.

Running "less:download" (less) task
>> 1 stylesheet created.

Running "less:main" (less) task
>> 1 stylesheet created.

Running "less:parts" (less) task
>> 1 stylesheet created.

Running "less:productManagement" (less) task
>> 1 stylesheet created.

Running "less:productStructure" (less) task
>> 1 stylesheet created.

Running "less:visualization" (less) task
>> 1 stylesheet created.

Running "less:workspaceManagement" (less) task
>> 1 stylesheet created.

Running "less:organizationManagement" (less) task
>> 1 stylesheet created.

Running "connect:livereload" (connect) task
Started connect web server on http://localhost:9001

Running "watch:dev" (watch) task
Waiting...

Thanks for your help

**Comment by mguimard** [comment]
This is the normal behavior, a development server is launched and is waiting for source code modification.
